# Explanation
# Version: Specifies which version of the Docker Compose file format is being used.
# Services: This section defines the containers that need to be created.

# app:
# build: Points to the Dockerfile in the current directory that will be used to build the image of the Golang app.
# ports: Maps port 8080 on the host to port 8080 on the container, allowing external access to the Go application.
# depends_on: Ensures that the db service is started before the app service.
# environment: Defines environment variables used by the Go application to connect to the PostgreSQL database.

# db:
# image: Uses the official PostgreSQL image.
# environment: Sets environment variables that configure the default database name, user, and password.
# ports: Maps port 5432 on the host to port 5432 on the container to allow direct database access.
# volumes: Maps a named volume pgdata for persistent storage of database data.
# Volumes: Defines persistent data volumes used by the services. In this case, pgdata is used to persist PostgreSQL data.

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ENV: development
      FILL: true
      MIGRATIONS: file://migrations
      DSN: postgresql://postgres:password@db:5434/schedule?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

    command: ["./demo-app"]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgresql://postgres:postgres@db:5434/schedule?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./pkg/schedule/migrations:/migrations


volumes:
  pgdata: