### Create Schedule Item
POST localhost:8081/api/v1/schedules
Content-Type: application/json

{
  "discipline": "1",
  "cabinet": "203",
  "timePeriod": "15-16"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get Schedule Item
GET localhost:8081/api/v1/schedules/2

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Schedule Item
PUT localhost:8081/api/v1/schedules/2
Content-Type: application/json

{
  "timePeriod": "13-16"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete Schedule Item
DELETE localhost:8081/api/v1/schedules/1
Content-Type: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}